# Generated by Django 4.2.3 on 2023-07-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionalStreet', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('customerType', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobilePhone', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('NIF', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_position', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PRESUPUESTO', 'Presupuesto'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PRESUPUESTO', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='store.order')),
                ('orderProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderproduct')),
            ],
        ),
    ]
